spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: ${MONGODB_URI_AI}
      database: fitnessRecommaendations
  rabbitmq:
    addresses: ${RABBITMQ_URL}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8671/eureka/}

RabbitMQ:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

Gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}