spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_tracker_user
    username: postgres
    password: RadheRadhe.02

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/
